--- #YAML:1.0
name: Time-TimeTick
version: 0.01
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Time::TimeTick:
    file: lib/Time/TimeTick.pm
    version: 0.01
generated_by: Module::Build version 0.21
